#!/usr/bin/env bash

dl(){
  curl "https://uupdump.net/get.php?id=${uuid}&pack=${lang}&edition=professional" \
    -H 'cache-control: max-age=0' \
    -H 'content-type: application/x-www-form-urlencoded' \
    -H 'origin: https://uupdump.net' \
    -H 'upgrade-insecure-requests: 1' \
    -H 'user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36 Edg/107.0.1418.35' \
    --data-raw 'autodl=3&updates=1&cleanup=1&netfx=1&virtualEditions%5B%5D=ProfessionalWorkstation&virtualEditions%5B%5D=ProfessionalEducation&virtualEditions%5B%5D=Education&virtualEditions%5B%5D=Enterprise&virtualEditions%5B%5D=ServerRdsh&virtualEditions%5B%5D=IoTEnterprise' \
    --compressed
}

dumpiti(){
  uuid="$1"
  lang="$2"
  if ! [[ -n "$uuid" ]]; then
    echo 'wrong num of args'
    return
  fi
  echo curl -sL "https://uupdump.net/get.php?id=${uuid}&pack=${lang}&edition=professional"
  dl > zip
  cat zip | busybox unzip -o -
  bash ./uup_download_linux.sh
}

dumpit "$@" zh-cn
dumpit "$@" en-us
